chart/urls.py
from django.urls import path
from .views import manager_chart, client_chart, get_messages, send_message, select_participant, start_conversation, conversation_messages

app_name = 'chart'
urlpatterns = [
    path('manager/chart/', manager_chart, name='manager-chart'),
    path('client/chart', client_chart, name='client-chart'),
    path('select-participant/', select_participant, name='select-participant'),
    path('start-conversation/<int:participant_id>/', start_conversation, name='start-conversation'),
    path('api/messages/<int:conversation_id>/', get_messages, name='get-messages'),
    path('api/messages/send/<int:conversation_id', send_message, name='send-messages'),
    path('conversation/<int:conversation_id>/', conversation_messages, name='conversation-messages'),  # New URL pattern
]

client/urls.py
from django.urls import path
from .views import indexview, ClientDashboardView

app_name = 'client'
urlpatterns = [
    path('', indexview, name='index'),
    path('dashboard/', ClientDashboardView.as_view(), name='client_dashboard'),
]

manacevak/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('client.urls')),
    path('manager/', include('manager.urls')),
    path('appointment/', include('appointment.urls')),
    path('user/', include('user.urls')),
    path('services/', include('services.urls')),
    path('chart/', include('chart.urls')),

]

manager/urls.py
from django.urls import path
from .views import dashboard

app_name = 'manager'
urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
]

services/urls.py
from django.urls import path
from . import views


app_name = 'services'
urlpatterns = [
    path('upload/', views.upload_service, name='upload_service'),
    path('display/', views.display_services, name='display_services'),
    path('services/', views.services_list, name='services_list'),
    path('request/<int:service_id>/', views.request_service, name='request_service'),
    path('requested/', views.display_requested_services, name='display_requested_services'),
]

user/urls.py
# users/urls.py

from django.urls import path
from .views import EmployeeLoginView, ClientLoginView, ClientSignUpView, ClientLogoutView, EmployeeLogoutView, manager_profile_view, client_profile_view, manager_user_update_view, client_user_update_view, manager_password_change_view, client_password_change_view


app_name = 'user'
urlpatterns = [
    path('login/employee/', EmployeeLoginView.as_view(), name='employee_login'),
    path('logout/employee/', EmployeeLogoutView.as_view(), name='employee_logout'),
    path('login/client/', ClientLoginView.as_view(), name='client_login'),
    path('logout/client/', ClientLogoutView.as_view(), name='client_logout'),
    path('signup/client/', ClientSignUpView.as_view(), name='client_signup'),
    path('profile/manager/', manager_profile_view, name='manager_profile'),
    path('dashboard/profile/client/', client_profile_view, name='client_profile'),
    path('manager/profile/update/', manager_user_update_view, name='manager_user_update'),
    path('client/profile/update/', client_user_update_view, name='client_user_update'),
    path('manager/password/change/', manager_password_change_view, name='manager_password_change'),
    path('client/password/change/', client_password_change_view, name='client_password_change'),

]
# In urls.py

manager/models.py
from django.db import models

# Create your models here.

manager/views.py
from django.shortcuts import render

# Create your views here.


def dashboard(request):
    return render(request, 'manager/dashboard.html')

manager/templates/manager/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'manager/css/manager.css' %}">
	<link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>

	<title>AdminSite</title>
</head>
<body>

	<!-- SIDEBAR -->
	<section id="sidebar">
		<a href="#" class="brand"><i class='bx bxs-smile icon'></i> AdminSite</a>
		<ul class="side-menu">
			<li><a href="{% url 'client:client_dashboard' %}" class="active"><i class='bx bxs-dashboard icon' ></i> Dashboard</a></li>
			<li class="divider" data-text="main">Main</li>
			<li>
				<a href="#"><i class='bx bxs-inbox icon' ></i> Services <i class='bx bx-chevron-right icon-right' ></i></a>
				<ul class="side-dropdown">
					<li><a href="{% url 'services:display_requested_services' %}">Service Request</a></li>
					<li><a href="{% url 'services:upload_service' %}">Upload</a></li>
					<li><a href="{% url 'services:services_list' %}">Service list</a></li>
					<li><a href="#">Button</a></li>
				</ul>
			</li>
			<li><a href="{% url 'chart:manager-chart' %}"><i class='bx bxs-chart icon' ></i> Charts</a></li>
			<li><a href="% url 'user:manager_profile' %}"><i class='bx bxs-widget icon' ></i>Settings </a></li>
			<li class="divider" data-text="table and forms">settingss</li>
			<li><a href="#"><i class='bx bx-table icon' ></i>Users</a></li>
			<li>
				<a href="#"><i class='bx bxs-notepad icon' ></i> LandingPage <i class='bx bx-chevron-right icon-right' ></i></a>
				<ul class="side-dropdown">
					<li><a href="#">Hero</a></li>
					<li><a href="#">ABout</a></li>
					<li><a href="#">Service</a></li>
					<li><a href="#">Pricing</a></li>
					<li><a href="#">Gallery</a></li>
				</ul>
			</li>
		</ul>
		<div class="ads">
			<div class="wrapper">
				<a href="" class="btn-upgrade">Upgrade</a>
				<p>Become a <span>PRO</span> member and enjoy <span>All Features</span></p>
			</div>
		</div>
	</section>
	<!-- SIDEBAR -->

	<!-- NAVBAR -->
	<section id="content">
		<!-- NAVBAR -->
		<nav>
			<i class='bx bx-menu toggle-sidebar' ></i>
			<form action="#">
				<div class="form-group">
					<input type="text" placeholder="Search...">
					<i class='bx bx-search icon' ></i>
				</div>
			</form>
			<a href="#" class="nav-link">
				<i class='bx bxs-bell icon' ></i>
				<span class="badge">5</span>
			</a>
			<a href="#" class="nav-link">
				<i class='bx bxs-message-square-dots icon' ></i>
				<span class="badge">8</span>
			</a>
			<span class="divider"></span>
			<div class="profile">
				<img src="https://images.unsplash.com/photo-1517841905240-472988babdf9?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8cGVvcGxlfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" alt="">
				<ul class="profile-link">
					<li><a href="#"><i class='bx bxs-user-circle icon' ></i> Profile</a></li>
					<li><a href="#"><i class='bx bxs-cog' ></i> Settings</a></li>
					<li><a href="#"><i class='bx bxs-log-out-circle' ></i> Logout</a></li>
				</ul>
			</div>
		</nav>
		<!-- NAVBAR -->

		<!-- MAIN -->
		<main>
			  {% block content %}
      <!-- Default content goes here -->
      {% endblock %}
		</main>
		<!-- MAIN -->
	</section>
	<!-- NAVBAR -->

	<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
	<script src="{% static 'manager/manager.js' %}"></script>
</body>
</html>

manager/templates/manager/dashboard.html
{% extends "manager/base.html" %}

{% block title %}About Us{% endblock %}

{% block content %}
    <h1>hey</h1>
    <p></p>
{% endblock %}

manager/templates/manager/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'client/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <title>Login</title>
</head>

<body>
           <!-- Login Form -->
        <div class="form-container sign-in">
            <form action="{% url 'user:client_login' %}" method="post">
                {% csrf_token %}
                <h1>Login</h1>
                <div class="social-icons">
                    <a href="#" class="icon"><i class="fa-brands fa-google-plus-g"></i></a>
                    <a href="#" class="icon"><i class="fa-brands fa-facebook-f"></i></a>
                    <a href="#" class="icon"><i class="fa-brands fa-github"></i></a>
                    <a href="#" class="icon"><i class="fa-brands fa-linkedin-in"></i></a>
                </div>
                <span>or use your email and password</span>
                <input type="text" name="username" placeholder="Username" required>
                <input type="password" name="password" placeholder="Password" required>
                <a href="{#}">Forgot Your Password?</a>
                <button type="submit">Login</button>
            </form>
        </div>

        <!-- Toggle Panel -->
        <div class="toggle-container">
            <div class="toggle">
                <div class="toggle-panel toggle-left">
                    <h1>Welcome Back</h1>
                    <p>Log in to access your dashboard</p>
                    <button class="hidden" id="login">Login</button>
                </div>
                <div class="toggle-panel toggle-right">
                    <h1>Hello Friend,</h1>
                    <p>Sign Up if you don't have an account.</p>
                    <button class="hidden" id="register">Sign Up</button>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'client/login.js' %}"></script>
</body>
</html>