manacevak/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('client.urls')),
    path('manager/', include('manager.urls')),
    path('appointment/', include('appointment.urls')),
    path('user/', include('user.urls')),
    path('services/', include('services.urls')),
    path('chart/', include('chart.urls')),

]

user/urls.py
# users/urls.py

from django.urls import path
from .views import EmployeeLoginView, ClientLoginView, ClientSignUpView, ClientLogoutView, EmployeeLogoutView, manager_profile_view, client_profile_view, manager_user_update_view, client_user_update_view, manager_password_change_view, client_password_change_view


app_name = 'user'
urlpatterns = [
    path('login/employee/', EmployeeLoginView.as_view(), name='employee_login'),
    path('logout/employee/', EmployeeLogoutView.as_view(), name='employee_logout'),
    path('login/client/', ClientLoginView.as_view(), name='client_login'),
    path('logout/client/', ClientLogoutView.as_view(), name='client_logout'),
    path('signup/client/', ClientSignUpView.as_view(), name='client_signup'),
    path('profile/manager/', manager_profile_view, name='manager_profile'),
    path('dashboard/profile/client/', client_profile_view, name='client_profile'),
    path('manager/profile/update/', manager_user_update_view, name='manager_user_update'),
    path('client/profile/update/', client_user_update_view, name='client_user_update'),
    path('manager/password/change/', manager_password_change_view, name='manager_password_change'),
    path('client/password/change/', client_password_change_view, name='client_password_change'),

]
# In urls.py

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    ROLE_CHOICES = [
        ('manager', 'Manager'),
        ('client', 'Client'),
        ('superuser', 'Superuser'),
    ]

    role = models.CharField(max_length=20, choices=ROLE_CHOICES)

    def is_manager(self):
        return self.role == 'manager'


    def is_client(self):
        return self.role == 'client'

    # No need for a separate is_superuser method, use the built-in


class UserProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    bio = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}'s Profile"

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from .models import CustomUser, UserProfile


# In forms.py


class ClientRegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password1', 'password2', 'email']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.role = 'client'  # Automatically assign role to 'client'
        if commit:
            user.save()
        return user


class AdminUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password1', 'password2', 'role']

    def clean_role(self):
        role = self.cleaned_data.get('role')
        if role not in ['manager']:
            raise forms.ValidationError("Only Manager  can be created with this form.")
        return role

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_picture', 'bio']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']  # Fields to update

    def clean_username(self):
        username = self.cleaned_data.get('username')
        # Check for existing usernames, excluding the current user
        if CustomUser.objects.exclude(pk=self.instance.pk).filter(username=username).exists():
            raise forms.ValidationError("This username is already taken.")
        return username


# Custom Password Change Form
class CustomPasswordChangeForm(PasswordChangeForm):
    class Meta:
        model = CustomUser
        fields = ['old_password', 'new_password1', 'new_password2']

    def clean_new_password2(self):
        new_password1 = self.cleaned_data.get('new_password1')
        new_password2 = self.cleaned_data.get('new_password2')
        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError("The two password fields didn't match.")
        return new_password2

user/views.py
# In views.py
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from .decorators import role_required
from django.shortcuts import render, redirect
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib import messages
from .forms import ClientRegistrationForm, ProfileUpdateForm, UserUpdateForm, CustomPasswordChangeForm
from .models import CustomUser, UserProfile



# In views.py
class EmployeeLoginView(LoginView):
    template_name = 'manager/login.html'
    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)

        # Redirect based on the user's role
        if user.role == 'manager':
            return redirect('manager:dashboard')

        else:
            return redirect('user:employee_login')  # For clients


class ClientLoginView(LoginView):
    template_name = 'client/login.html'  # Separate login template for clients
    success_url = reverse_lazy('client:client_dashboard')  # URL after successful client login

    def form_valid(self, form):
        user = form.get_user()
        if user.role == 'client':
            login(self.request, user)
            return redirect(self.success_url)
        else:
            return redirect('client:index')



class ClientSignUpView(CreateView):
    model = CustomUser
    form_class = ClientRegistrationForm
    template_name = 'client/login.html'
    success_url = reverse_lazy('client:client_dashboard')  # Redirect to client dashboard after sign-up

    def form_valid(self, form):
        # Optionally, you can add any custom logic before saving the user
        return super().form_valid(form)


class ClientLogoutView(LogoutView):  # Fix indentation
    next_page = reverse_lazy('user:client_login')  # Redirect to client login page after logout


class EmployeeLogoutView(LogoutView):  # Fix indentation
    next_page = reverse_lazy('user:employee_login')



def manager_profile_view(request):
    user_profile, created = UserProfile.objects.get_or_create(user=request.user)

    form = ProfileUpdateForm(instance=user_profile)
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('user:manager_profile')
        else:
            form = ProfileUpdateForm(instance=user_profile)


    return render(request, 'user/manager_profile.html', {'form': form})

@login_required
@role_required('client')
def client_profile_view(request):
    user_profile, created = UserProfile.objects.get_or_create(user=request.user)


    form = ProfileUpdateForm(instance=user_profile)

    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('user:client_profile')


    return render(request, 'user/client_profile.html', {'form': form})


@login_required
@role_required('manager')
def manager_user_update_view(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile has been updated successfully!')
            return redirect('user:manager_user_update')
    else:
        form = UserUpdateForm(instance=request.user)  # This line handles GET requests

    return render(request, 'user/manager_update.html', {'form': form})


def client_user_update_view(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile has been updated successfully!')
            return redirect('user:client_user_update')
    else:
        form = UserUpdateForm(instance=request.user)  # This line handles GET requests

    return render(request, 'user/client_update.html', {'form': form})

@login_required
@role_required('manager')
def manager_password_change_view(request):
    if request.method == 'POST':
        password_form = CustomPasswordChangeForm(user=request.user, data=request.POST)
        if password_form.is_valid():
            password_form.save()
            messages.success(request, 'Your password has been changed successfully!')
            return redirect('user:employee_login')  # Redirect to the login page or another page
    else:
        password_form = CustomPasswordChangeForm(user=request.user)

    return render(request, 'user/manager_password.html', {'password_form': password_form})


@login_required
@role_required('client')
def client_password_change_view(request):
    if request.method == 'POST':
        password_form = CustomPasswordChangeForm(user=request.user, data=request.POST)
        if password_form.is_valid():
            password_form.save()
            messages.success(request, 'Your password has been changed successfully!')
            return redirect('user:client_login')  # Redirect to the login page or another page
    else:
        password_form = CustomPasswordChangeForm(user=request.user)

    return render(request, 'user/client_password.html', {'password_form': password_form})

user/templates/user/client_password.html
{% block title %}Change Password - Client{% endblock %}

{% block content %}
<div class="container">
    <h2>Change Password - Client</h2>
    <form method="POST">
        {% csrf_token %}
        {{ password_form.as_p }}
        <button type="submit" class="btn btn-primary">Change Password</button>
    </form>
    <p><a href="{% url 'user:client_profile' %}">Back to Profile</a></p>
</div>
{% endblock %}

user/templates/user/client_profile.html
<!-- client_profile.html -->
<h2>Edit Profile</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Changes</button>
    li><a href="{% url 'user:client_password_change' %}"><i class='bx bxs-user-circle icon' ></i> Change password</a></li>
        <li><a href="{% url 'user:client_user_update' %}"><i class='bx bxs-user-circle icon' ></i> update username</a></li>
</form>

user/templates/user/client_update.html
{% block content %}
<h2>Client: Update Username and Email</h2>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
{% endif %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update Profile</button>
    <p><a href="{% url 'user:client_profile' %}">Back to Profile</a></p>
</form>
{% endblock %}

user/templates/user/manager_password.html
{% block title %}Change Password - Manager{% endblock %}

{% block content %}
<div class="container">
    <h2>Change Password - Manager</h2>
    <form method="POST">
        {% csrf_token %}
        {{ password_form.as_p }}
        <button type="submit" class="btn btn-primary">Change Password</button>
    </form>
    <p><a href="{% url 'user:manager_user_update' %}">Back to Profile</a></p>
</div>
{% endblock %}

user/templates/user/manager_profile.html
<!-- manager_profile.html -->
<h2>Edit Profile</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Changes</button>
    <li><a href="{% url 'user:manager_password_change' %}"><i class='bx bxs-user-circle icon' ></i> Change password</a></li>
        <li><a href="{% url 'user:manager_user_update' %}"><i class='bx bxs-user-circle icon' ></i> update username</a></li>

</form>

user/templates/user/manager_update.html
{% block content %}
<h2>Manager: Update Username and Email</h2>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
{% endif %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update Profile</button>
</form>
{% endblock %}